spring:
  elasticsearch:
    bboss:
      elasticsearch:
        rest:
          hostNames: 127.0.0.1:9200  # es服务ip:端口  集群用逗号隔开  如果是https协议   https://ip+端口 多个逗号隔开
        sliceScrollThreadCount: 100  # slice scroll 查询线程数
        sliceScrollThreadQueue: 100  # slice scroll 查询等待队列数
        sliceScrollBlockedWaitTimeout: 0 #单位毫秒
        # 访问容器环境/云环境或者其他通过代理转发环境中部署的Elasticsearch时，请关闭：elasticsearch.discoverHost=false
        discoverHost: false     # 集群节点自动发现discover控制开关 如果开启discover机制，客户端就会具备自动发现新增的ES集群节点的能力，elasticsearch.rest.hostNames中就可以只配置初始的几个节点，不需要配置全部节点。
        showTemplate: true      # DSL脚本调试日志开关，将showTemplate设置为true，同时将日志级别设置为INFO，则会将query dsl脚本输出到日志文件中：
        includeTypeName: true   # 向下兼容
        slowDslThreshold: 1000  # 定义慢dsl耗时阈值，执行时间长超过指定阈值的dsl为慢dsl，必须指定大于0的数值
        slowDslCallback: com.ktz.deploy.elasticsearch #如果没有指定回调处理接口，将直接打印警告信息到日志文件，WARN级别 ， 如果dsl过长，需要截取掉部分内容再打印到日志文件中:超过2048的dsl将被截取掉超过的内容，替换为.....，否则调用SlowDslCallback接口方法slowDslHandle传递慢dsl的相关信息
      http:
        maxTotal: 600             # 最大连接数
        defaultMaxPerRoute: 200   # 每个地址允许的最大连接数
        retryTime: 3              # 连接失败重试次数
        timeoutConnection: 10000  # 建立连接超时时间
        timeoutSocket: 50000      # socket通讯超时时间，如果在通讯过程中出现sockertimeout异常，可以适当调整timeoutSocket参数值，单位：毫秒
        connectionRequestTimeout: 10000  # 申请连接超时时间，设置为0不超时
      dslfile:
        refreshInterval: -1  # dsl配置文件热加载扫描时间间隔，毫秒为单位，默认5秒扫描一次，<= 0时关闭扫描机制
    rest:
      uris: localhost:9200