spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/problem?characterEncoding=utf8&useUnicode=true&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimum-idle: 5             # 最小空闲连接数
      idle-timeout: 600000        # 空闲连接存货最大时间，默认600000（10分钟）
      maximum-pool-size: 10       # 连接池最大连接数
      auto-commit: true           # 控制从池返回的连接的默认自动提交行为，默认值：tree
      pool-name: MyHikariCP       # 连接池名字
      max-lifetime: 1800000       # 控制池中连接的最长生命周期，值0表示无线生命周期，默认1800000即30分钟
      connection-timeout: 30000   # 数据库连接超时时间，默认30秒 30000，如果在没有可用连接的情况下超过此时间，则会抛出SQLException。最低可接收的连接超时时间为250ms
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.ktz.deploy.hikaricp.entity
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
