spring:
  redis:
    host:                 # Redis服务器地址
    port: 6379            # Redis服务器端口
    database: 0           # 数据库索引
    password: ktz_sh      # Redis服务器连接密码
    timeout: 3000         # Redis连接超时时间
    # jedis是直连模式，在多个线程间共享一个Jedis实例是线程不安全的，每个线程都去拿自己的Jedis实例，当连接数量增多时，物理连接成本就较高了
    # lettuce的连接是基于Netty的，连接实例可以在多个线程间共享，大致意思就是一个多线程的应用可以使用同一个连接实例，而不用担心并发线程的数量。通过异步的方式可以让我们更好地利用系统资源
    lettuce:
      pool:
        max-idle: 300 # 连接池中的最大空闲连接  默认 8
        min-idle: 5 # 连接池中的最小空闲连接 默认 0
        max-active: 600  # 连接池最大连接数（使用负值表示没有限制）默认 8
        max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
