server:
  undertow:
    accesslog:
      dir: logs           # 日志存放目录
      enabled: false      # 是否启动日志
      pattern: common     # 日志格式
      prefix: access_log  # 日志文件名前缀
      suffix: log         # 日志文件名后缀
    io-threads: 16        # 设置IO线程数，它主要执行非阻塞任务，它们会负责多个连接，默认设置每个CPU核心一个线程，不要设置过大
    worker-threads: 256   # 阻塞任务线程池，当执行类似servlet请求阻塞IO操作，undertow会从这个线程池中取得线程，它的值设置取决于系统线程执行任务的阻塞系数，默认值是IO线程数* 8
    buffer-size: 1024     # 这个配置会影响buffer，这些buffer会用于服务器连接的IO操作，有点类似Netty的池化内存管理，每块buffer的空间大小，越小的空间被利用越充分，不要设置太大，以免影响其他应用
    direct-buffers: true  # 是否分配直接内存（NIO直接分配堆外内存）
    max-http-post-size: 0 # HTTP POST 请求最大的大小
